### ISSUE TITLE
autobahn requirement

### ISSUE THREAD

**Issue by cancan101** [pebble/homebrew-pebble-sdk#26]
What is / was `autobahn` being used for in the Pebble SDK?

**Comment by Katharine** [comment]
Nothing.

**Comment by cancan101** [comment]
Was it ever used for anything? I see that it was recently removed: https://github.com/pebble/homebrew-pebble-sdk/commit/1487048a46eddd115201aa151819a48d1fb6926b#diff-2a8eb022192f4b8ffe5d68d57e1f732b

**Comment by Katharine** [comment]
Not since 2.0-beta1 or something. A long time ago, the developer connection was reversed — the SDK ran a websocket server, and the phone connected to it. It was used there.

We actually once again have websocket servers (the phone simulator is one), but that functionality is now provided by gevent and gevent-websocket.

The twisted and autobahn requirements are just long-dead remnants that nobody had removed.

**Comment by Katharine** [comment]
Upon actually checking, this change was [actually made in 2.0-dp2](https://developer.getpebble.com/sdk/changelogs/2.0-DP2/), back when SDK 2 was under NDA.
